/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArtPlayer: typeof import('./src/components/Artplayer/ArtPlayer.vue')['default']
    Aside: typeof import('./src/components/Layout/Aside.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElText: typeof import('element-plus/es')['ElText']
    Header: typeof import('./src/components/Layout/Header.vue')['default']
    Home: typeof import('./src/components/Home/Home.vue')['default']
    IconClarityWindowRestoreLine: typeof import('~icons/clarity/window-restore-line')['default']
    IconEpFullScreen: typeof import('~icons/ep/full-screen')['default']
    IconFluentMaximize: typeof import('~icons/fluent/maximize')['default']
    IconFluentmaximize16Regular: typeof import('~icons/fluent/maximize16-regular')['default']
    IconFluentmaximize30Regular: typeof import('~icons/fluent/maximize30-regular')['default']
    IconFluentmaximize48Filled: typeof import('~icons/fluent/maximize48-filled')['default']
    IconFluentMaximize48filled: typeof import('~icons/fluent/maximize48filled')['default']
    IconFluentMaximize48Filled: typeof import('~icons/fluent/maximize48-filled')['default']
    IconFluentmaximize48Regular: typeof import('~icons/fluent/maximize48-regular')['default']
    IEpFullScreen: typeof import('~icons/ep/full-screen')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
